### ISSUE TITLE
`alignment` method is not working for a LORRI object where the image is at the edge of the frame

### ISSUE THREAD

**Issue by ishan-mishra** [seignovert/galileo-ssi#2]
Hi Benoit! After using appropriate spice functions to get the geometric backplanes for a New Horizons LORRI image cube (lor_0299148263_0x630), I got a .pho.cub file. I loaded this .pho.cub file into python as a LORRI object. When I plot the data layer and the observation geometry layers on top of each other, there is an obvious misalignment (see attached file)

![misalignment](https://github.com/seignovert/galileo-ssi/assets/44908596/0e12185d-bf88-43fa-9ed7-92c011c11ff0)

To align the layers, I tried using the `alignment` method, but it did not work. The offsets being calculated for this specific image are 0. I suspect this is because the image only contains a partial disk on one edge of the frame, rather than a full planetary disk. Thought I should bring it to your attention.

**Comment by seignovert** [comment]
Hi @ishan-mishra,

Yes, I confirm, the `alignment=True` parameter is performing a **best effort alignment** that should work on full disc images but could fail if the disk is partially in the FoV. In these cases, you should by-pass it manually, eg. `LORRI('lor_0299148263_0x630', offset_l=N, offset_s=M)`. In some case, `N` and `M` can be ten's of pixels.

The alignment can also be changed after the image loaded to improve it step by step (`img.alignment(offset_s=N)`).
I attach [a notebook](https://github.com/seignovert/galileo-ssi/files/13544654/Europa_img_alignment_example.zip) were you can see an example of this. To check the result, I sum all the pixels intensity along each axis to see if there is an offset remaining:

![image](https://github.com/seignovert/galileo-ssi/assets/13715971/ff9b3da7-3bae-40f1-bbe2-028b1f99c9bf)

I'm closing this issue for now because I don't have a simple solution to improve this auto-alignment method. If you happen to find a best approach, feel free to re-open it and submit a PR.

**Comment by ishan-mishra** [comment]
Thanks for confirming!
